"""
Pydantic v2 schemas for the DHARTI OS prediction API.

Defines the unified request/response contracts used by POST /predict,
plus the GET /health and GET /status response models.

NOTE ON FEATURE NAMES
----------------------
All three schemas below mirror the exact column names each model's
sklearn Pipeline was trained on. The saved `.pkl` files are full
Pipelines (including preprocessing such as OneHotEncoder for categorical
columns), so services build a single-row DataFrame with these exact
column names and call `pipeline.predict()` directly — no manual
encoding is performed here or in the services.
"""

from typing import Any

from pydantic import BaseModel, Field


class CropYieldInput(BaseModel):
    """
    Input features for the crop yield model.
    Column names match the training data exactly:
    Crop, Season, State (categorical) and Crop_Year, Area,
    Annual_Rainfall, Fertilizer, Pesticide (numeric).
    """

    Crop: str = Field(..., description="Crop name, e.g. 'Rice'")
    Season: str = Field(..., description="Growing season, e.g. 'Kharif'")
    State: str = Field(..., description="Indian state, e.g. 'Punjab'")
    Crop_Year: int = Field(..., description="Year of cultivation")
    Area: float = Field(..., description="Cultivated area (hectares)")
    Annual_Rainfall: float = Field(..., description="Annual rainfall (mm)")
    Fertilizer: float = Field(..., description="Fertilizer used (kg)")
    Pesticide: float = Field(..., description="Pesticide used (kg)")


class FloodInput(BaseModel):
    """
    Input features for the flood prediction model.

    Column names match the training data exactly:
    Land_Cover, Soil_Type (categorical) and Rainfall, Temperature,
    Humidity, River_Discharge, Water_Level, Elevation,
    Population_Density, Infrastructure, Historical_Floods (numeric).
    """

    Land_Cover: str = Field(..., description="Land cover type, e.g. 'Forest'")
    Soil_Type: str = Field(..., description="Soil type, e.g. 'Clay'")
    Rainfall: float = Field(..., description="Rainfall (mm)")
    Temperature: float = Field(..., description="Temperature (Celsius)")
    Humidity: float = Field(..., description="Relative humidity (%)")
    River_Discharge: float = Field(..., description="River discharge (m3/s)")
    Water_Level: float = Field(..., description="Water level (m)")
    Elevation: float = Field(..., description="Elevation (m)")
    Population_Density: float = Field(..., description="Population density (people/km2)")
    Infrastructure: float = Field(..., description="Infrastructure score/index")
    Historical_Floods: float = Field(..., description="Count/index of historical floods")


class CropRecommendationInput(BaseModel):
    """
    Input features for the crop recommendation model.

    Column names match the training data exactly:
    N, P, K, temperature, humidity, ph, rainfall.
    """

    N: float = Field(..., description="Nitrogen content in soil")
    P: float = Field(..., description="Phosphorus content in soil")
    K: float = Field(..., description="Potassium content in soil")
    temperature: float = Field(..., description="Temperature in Celsius")
    humidity: float = Field(..., description="Relative humidity in %")
    ph: float = Field(..., description="Soil pH value")
    rainfall: float = Field(..., description="Rainfall in mm")


class PredictionRequest(BaseModel):
    """Unified request body for POST /predict."""

    latitude: float = Field(
        ..., description="Latitude of the farm location."
    )

    longitude: float = Field(
        ..., description="Longitude of the farm location."
    )

    language: str = Field(    
        default="en",
        description="User preferred language (en, hi, mr, ta, etc.)"
    )

    crop_yield: CropYieldInput
    flood: FloodInput
    crop_recommendation: CropRecommendationInput

class RecommendationItem(BaseModel):
    """Single recommendation generated by the Decision Engine."""

    priority: str = Field(
        ..., description="Priority of this recommendation (HIGH, MEDIUM, LOW)."
    )

    message: str = Field(
        ..., description="Recommendation message."
    )

class WeatherResponse(BaseModel):
    """Current weather information."""

    temperature: float = Field(..., description="Current temperature in Celsius.")
    humidity: int = Field(..., description="Current relative humidity (%).")
    pressure: int = Field(..., description="Atmospheric pressure (hPa).")
    weather: str = Field(..., description="General weather condition.")
    description: str = Field(..., description="Detailed weather description.")
    wind_speed: float = Field(..., description="Wind speed (m/s).")

class DecisionResponse(BaseModel):
    """Decision Engine output returned alongside model predictions."""

    risk_score: int = Field(
        ..., ge=0, le=100,
        description="Overall agricultural risk score (0-100)."
    )

    risk_level: str = Field(
        ..., description="Overall agricultural risk level."
    )

    priority: str = Field(
        ..., description="Overall priority level."
    )

    yield_status: str = Field(
        ..., description="Expected crop yield category."
    )

    recommended_crop: str = Field(
        ..., description="Recommended crop."
    )

    summary: str = Field(
        ..., description="Short AI-generated decision summary."
    )

    recommendations: list[RecommendationItem] = Field(
        ...,
        description="Prioritized actionable recommendations."
    )


class PredictionResponse(BaseModel):
    """Unified response body for POST /predict."""

    crop_yield_prediction: Any = Field(
        ..., description="Raw crop yield model output."
    )

    flood_prediction: Any = Field(
        ..., description="Raw flood prediction model output."
    )

    crop_recommendation_prediction: Any = Field(
        ..., description="Raw crop recommendation model output."
    )

    weather: WeatherResponse | None = Field(
        default=None,
        description="Current weather information from OpenWeatherMap."
    )

    decision: DecisionResponse = Field(
        ..., description="Decision Engine output."
    )

    ai_advisory: str | None = Field(
        default=None,
        description="AI-generated farmer advisory."
    )


class HealthResponse(BaseModel):
    """Response body for GET /health."""

    status: str
    models_loaded: bool


class ModelStatusDetail(BaseModel):
    """Per-model load status, used inside GET /status."""

    loaded: bool
    error: str | None = None


class StatusResponse(BaseModel):
    """Response body for GET /status."""

    models: dict[str, ModelStatusDetail]
    all_loaded: bool


class SoilResponse(BaseModel):
    """Response body for GET /soil (ISRIC SoilGrids)."""

    latitude: float = Field(..., description="Resolved latitude used for lookup.")
    longitude: float = Field(..., description="Resolved longitude used for lookup.")
    requested_latitude: float = Field(..., description="Original requested latitude.")
    requested_longitude: float = Field(..., description="Original requested longitude.")
    source: str = Field(default="ISRIC SoilGrids")
    available: bool = Field(..., description="Whether SoilGrids returned property data.")
    wrb_class: str | None = Field(default=None, description="WRB soil classification.")
    phh2o: float | None = Field(default=None, description="Soil pH in H2O.")
    nitrogen: float | None = Field(default=None, description="Total nitrogen (g/kg).")
    sand: float | None = Field(default=None, description="Sand content (%).")
    clay: float | None = Field(default=None, description="Clay content (%).")
    silt: float | None = Field(default=None, description="Silt content (%).")
    organic_carbon: float | None = Field(default=None, description="Soil organic carbon (g/kg).")
    cec: float | None = Field(default=None, description="Cation exchange capacity (cmol/kg).")
    bulk_density: float | None = Field(default=None, description="Bulk density (kg/dm³).")
    soil_organic_matter: float | None = Field(default=None, description="Soil organic matter (g/kg).")
    soil_type: str | None = Field(default=None, description="Derived texture class for flood model.")
    model_n: int | None = Field(default=None, description="Estimated N for crop recommendation model.")
    model_p: int | None = Field(default=None, description="Estimated P for crop recommendation model.")
    model_k: int | None = Field(default=None, description="Estimated K for crop recommendation model.")